#
# liquid-level-sensor-qdy30a.yaml -- ESPhome config to read QDY30A RS485 liquid level sensor
#
# (C) 2023 Hajo Noerenberg
#
# Usage: Connect RS485 adapter HW-0519 to pin D5/D6, connect QDY30A to RS485
#
# http://www.noerenberg.de/
# https://github.com/hn/esphome-configs
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.0 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
#

esphome:
  name: liquid-level-sensor-qdy30a
  friendly_name: Liquid level sensor QDY30A

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Liquid Sensor Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

uart:
  id: modbus_uart
  tx_pin: D6
  rx_pin: D5
  baud_rate: 9600

modbus:
  #flow_control_pin: D7
  send_wait_time: 300ms
  id: modbus_hw

modbus_controller:
  - id: modbus_master
    address: 0x1
    modbus_id: modbus_hw
    setup_priority: -10
    update_interval: 2s

sensor:
  - platform: template
    id: water_volume
    name: Water volume
    device_class: volume_storage
    state_class: measurement
    icon: mdi:water
    unit_of_measurement: L
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 20.0 -> 0
          - 80.0 -> 1000
  - platform: modbus_controller
    modbus_controller_id: modbus_master
    id: liquid_level
    name: Liquid level
    register_type: holding
    value_type: S_WORD
    address: 0x0004
    force_new_range: true
    device_class: distance
    state_class: measurement
    icon: mdi:car-coolant-level
    unit_of_measurement: cm
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - throttle_average: 20s
    on_value:
      then:
        - lambda: "id(water_volume).publish_state(truncf(x*10)/10);"
  - platform: modbus_controller
    modbus_controller_id: modbus_master
    name: Liquid level minimum
    register_type: holding
    value_type: S_WORD
    address: 0x0005
    skip_updates: 200
    entity_category: diagnostic
    device_class: distance
    icon: mdi:format-vertical-align-bottom
    unit_of_measurement: cm
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: modbus_master
    name: Liquid level maximum
    register_type: holding
    value_type: S_WORD
    address: 0x0006
    skip_updates: 200
    entity_category: diagnostic
    device_class: distance
    icon: mdi:format-vertical-align-top
    unit_of_measurement: cm
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

number:
  - platform: modbus_controller
    name: ModBus address
    register_type: holding
    address: 0x0000
    entity_category: config
    icon: mdi:numeric
    skip_updates: 200
    mode: box
    min_value: 1
    max_value: 255
    write_lambda: "return {};" # disable updates, remove if needed - not tested

select:
  - platform: modbus_controller
    name: Baud rate
    address: 0x0001
    entity_category: config
    icon: mdi:speedometer
    skip_updates: 200
    optionsmap:
      "1200": 0
      "2400": 1
      "4800": 2
      "9600": 3
      "19200": 4
      "38400": 5
      "57600": 6
      "115200": 7
    write_lambda: "return {};" # disable updates, remove if needed - not tested
  - platform: modbus_controller
    name: Pressure unit
    address: 0x0002
    entity_category: config
    icon: mdi:alpha-u-circle-outline
    skip_updates: 200
    optionsmap:
      "Unknown": 0
      "cm": 1
      "mm": 2
      "mPa": 3
      "Pa": 4
      "kPa": 5
      "MA": 6
    write_lambda: "return {};" # disable updates, remove if needed - not tested
  - platform: modbus_controller
    name: Decimal points
    address: 0x0003
    entity_category: config
    icon: mdi:decimal-comma-decrease
    skip_updates: 200
    optionsmap:
      "####": 0
      "###.#": 1
      "##.##": 2
      "#.###": 3
    write_lambda: "return {};" # disable updates, remove if needed - not tested
