#
# garden-monitor-hama-gm-300-sensor.yaml -- HAMA GM-300 garden monitor include file
#
# ! This file is to be included as a package in an ESPhome definition !
#
# (C) 2023 Hajo Noerenberg
#
# http://www.noerenberg.de/
# https://github.com/hn/esphome-configs
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.0 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
#

binary_sensor:
  - platform: template
    id: gm300_c${channel}_battery_low
    name: "${desc}: Battery"
    device_class: battery
    entity_category: diagnostic
  - platform: template
    id: gm300_c${channel}_forced_send
    name: "${desc}: Forced send"
    entity_category: diagnostic
    icon: mdi:gesture-tap-button

sensor:
  - platform: template
    id: gm300_c${channel}_soil_temperature
    name: "${desc}: Soil temperature"
    device_class: temperature
    state_class: measurement
    icon: mdi:coolant-temperature
    filters:
      - multiply: 0.1
  - platform: template
    id: gm300_c${channel}_air_temperature
    name: "${desc}: Air temperature"
    device_class: temperature
    state_class: measurement
    icon: mdi:sun-thermometer-outline
    filters:
      - multiply: 0.1
  - platform: template
    id: gm300_c${channel}_moisture
    name: "${desc}: Moisture"
    device_class: moisture
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 33.333
  - platform: template
    id: gm300_c${channel}_randomid
    name: "${desc}: Random boot id"
    entity_category: diagnostic
    icon: mdi:numeric
    accuracy_decimals: 0
